// The program is a collection of scripts.
// 
// There is one install script, one removal script, and multiple event scripts.
// The install script start tag may be implicitly defined at the start of a file.
// Likewise both the install script and removal script end tags may be implicitly defined.
// Event scripts are always well defined.
program = _{ SOI ~ (install_script | remove_script | event_script)* }
