condition_eq = { "=" | ^"eq" }
condition_ge = { ">=" | ^"ge" }
condition_gt = { ">" | ^"gt" }
condition_le = { "<=" | ^"le" }
condition_ne = { "<>" | ^"ne" }
condition_lt = { "<" | ^"lt" }

condition_operator = _{
    condition_eq
  | condition_ge
  | condition_gt
  | condition_le
  | condition_ne
  | condition_lt
}
condition_and      =  { ^"and" }
condition_or       =  { ^"or" }

condition_join = _{ condition_and | condition_or }
