pub enum ScriptType {
    Deactivate = 0,
    Activate1 = 1,
    Activate2 = 2,
    Hit = 3,
    Pickup = 4,
    Drop = 5,
    Collision = 6,
    Bump = 7,
    Timer = 9,
    Eat = 12,
    StartHoldHands = 13,
    StopHoldHands = 14,
    // 16-30 is creature attention on agent
    QuiescentOnAgent = 16,
    Activate1OnAgents = 17,
    Activate2OnAgents = 18,
    DeactivateOnAgents = 19,
    ApproachOnAgents = 20,
    RetreatOnAgents = 21,
    PickupOnAgents = 22,
    DropOnAgents = 23,
    NeedOnAgents = 24,
    RestOnAgents = 25,
    WestOnAgents = 26,
    EastOnAgents = 27,
    EatOnAgents = 28,
    HitOnAgents = 29,
    // Script 32-47 create on creature attention
    QuiescentOnCreatures = 32,
    Activate1OnCreatures = 33,
    Activate2OnCreatures = 34,
    DeactivateOnCreatures = 35,
    ApproachOnCreatures = 36,
    RetreatOnCreatures = 37,
    PickupOnCreatures = 38,
    DropOnCreatures = 39,
    NeedOnCreatures = 40,
    RestOnCreatures = 41,
    WestOnCreatures = 42,
    EastOnCreatures = 43,
    EatOnCreatures = 44,
    HitOnCreatures = 45,
    //
    Flinch = 64,
    LayEgg = 65,
    Sneeze = 66,
    Cough = 67,
    Shiver = 68,
    Sleep = 69,
    Fainting = 70,
    Unassigned = 71,
    Die = 72,
    //
    RawKeyDown = 73,
    RawKeyUp = 74,
    RawMouseMove = 75,
    RawMouseDown = 76,
    RawMouseUp = 77,
    RawMouseWheel = 78,
    RawTranslatedChar = 79,
    //
    UiMouseDown = 92,
    //
    PointerActivate1 = 101,
    PointerActivate2 = 102,
    PointerDeactivate = 103,
    PointerPickup = 104,
    PointerDrop = 105,
    PointerPortSelect = 110,
    PointerPortConnect = 111,
    PointerPortDisconnect = 112,
    PointerPortCancel = 113,
    PointerPortError = 114,
    PointerClickedBackground = 116,
    PointerActionDispatch = 117,
    ConnectionBreak = 118,
    //
    SelectedCreatureChanged = 120,
    VehiclePickup = 121,
    VehicleDrop = 122,
    WindowResized = 123,
    GotCarriedAgent = 124,
    LostCarriedAgent = 125,
    MakeSpeechBubble = 126,
    LifeEvent = 127,
    WorldLoaded = 128,
    Mate = 200,
    AgentException = 255,
}
